### PR TITLE
fix: Remove unused icon css

### PR DESCRIPTION
**Pull request by fsbraun**
djangocms-admin-style adds its own icon font (for the well-known symbols to add etc.). Besides providing css to style the admin the package adds css to allow using those icons by other apps in the admin.

* The use is deprecated since the djangocms-admin-style package is optional and hence the availability of the icon css on admin pages is not guaranteed.
* Over time the icons (both in terms of which and how they look) have stated deviating from the django-cms core's icons.
* This the same icons are at different positions in the icon fonts.

This PR removes the css for using the djangocms-admin-style icons in other apps to avoid the conflict between the icon positions. The icons themselves remain untouched and will appear as usual.

### CODE REVIEW

**Review by marksweb — APPROVED** [review]

**Comment by fsbraun** [comment]
Thanks!

**Comment by DmytroLitvinov** [comment]
Hi @marksweb ,
We are still using djangocms-admin-style and django-admin-shortcuts and we found out that starting version 3.2.1 shortcuts are not aligned. Can we move back `@import "components/shortcuts";` into a new version? 
The solution I used to make it work for us was taken from that issue https://github.com/alesdotio/django-admin-shortcuts/issues/34

**Comment by marksweb** [comment]
@DmytroLitvinov Is `components/shortcuts` specific to icons in that package?

**Comment by DmytroLitvinov** [comment]
Seems like not. 
So I think `icon` function can be removed file `components/shortcuts`

**Comment by fsbraun** [comment]
@DmytroLitvinov Thanks for pointing out this issue! 

**Can you check if this solution works for you**: Replace the `djangocms-admin-style` requirement by  `git+https://github.com/fsbraun/djangocms-admin-style@fix/django_shortcuts` ?

It includes the styling but not the icons.

Is so, I can immediately create the PR.

**Comment by DmytroLitvinov** [comment]
@fsbraun ,

Yes, it works 👍
image

**Comment by fsbraun** [comment]
@DmytroLitvinov See #480 and #481

**Pull request merged**
