### PR TITLE
feat: Add Django 4.2 admin support

### PR DESCRIPTION
**Pull request by fsbraun**
Django admin styles have changed. This fixes the delete-link styling and the readonly-fields styling

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
Hi @fsbraun ,
Seems like that Pull Request can fix issue we have at our stage server when we upgraded to Django@4.2 and we have read-only fields. 

I will look into details and let you know if it fixes so we can merge and release new version of djangocms-admin-style

**Comment by DmytroLitvinov** [comment]
@fsbraun , should it looks like that way? 
image

**Comment by fsbraun** [comment]
@DmytroLitvinov IMHO it should look like a form with editable fields, but the inputs replaced by the fields' values. Would you expect something else?

**Comment by DmytroLitvinov** [comment]
For me it is fine that it looks like that way. 

Also attaching how it looks for Django@4.2 without djangocms-admin-style
image

**Review by vinitkumar — APPROVED** [review]

**Pull request merged**
