### PR TITLE
feat: Release 3.3

### PR DESCRIPTION
**Pull request by fsbraun**
The PR adds back flex styling for multicolumn field sets to increase compatibility with Django 4.2+ admin styles.

Fixes a margin issue with checkbox helptexts

### CODE REVIEW

**Review by marksweb — APPROVED** [review]

**Review by DmytroLitvinov — APPROVED** [review]

**Comment by DmytroLitvinov** [comment]
Hi @fsbraun ,
Not sure, but may I ask if that issue is fixed in that PR?
image

**Comment by fsbraun** [comment]
Should. But I'd appreciate if you could check. Can you install from my patch and test?

`pip install git+https://github.com/fsbraun/djangocms-admin-style@chore/bump-to-3.2.8`

**Comment by DmytroLitvinov** [comment]
@fsbraun , no branch like `chore/bump-to-3.2.8`
image

**Comment by DmytroLitvinov** [comment]
Should be from `django-cms` organization - `pip install git+https://github.com/django-cms/djangocms-admin-style@chore/bump-to-3.2.8`

**Comment by DmytroLitvinov** [comment]
Seems like fixed.

image

**Pull request merged**
