### PR TITLE
chore: Update build system

### LINKED ISSUE #513: Documentation proposal for installation error of frontend packages
I got an error when installing the frontend packages with the `npm install` command.
The source of the error was the canvas package. Luckily this [StackOverflow post](https://stackoverflow.com/questions/64562563/how-can-i-ovecome-this-error-in-npm-install) saved my day. I had to download the [compiling dependencies](https://github.com/Automattic/node-canvas) for the canvas package on my Ubuntu 20.04 machine.

Then I thought this error might happen whenever someone tried a fresh installation of the frontend packages. Has anyone encountered this error when installing the frontend packages before? How common does this error occur?

If this is a common error, we should document it and I'm ready to work on documenting it if it's worth doing so.

What is your experience?

### PR DESCRIPTION
**Pull request by fsbraun**
This PR updates the build system

* Node.js 20
* Updated requirements
* Implicit canvas dependency is gone (fixing #513?)

@erkesando Can you check if you can install from this fix (you can install the fix into your venv using `pip install -e git+https://github.com/django-cms/djangocms-admin-style@chore/update-build-system`)?

Pending: Update of webpack.config.js.

### CODE REVIEW

**Review by vinitkumar — APPROVED** [review]
Looks good. Have you tried building the assets using this new build system?

**Comment by fsbraun** [comment]
Sure! Works nicely.

**Comment by vinitkumar** [comment]
> Sure! Works nicely.

@fsbraun Shouldn't we also commit the built files in the same PR, so is there no diff for them?

**Comment by fsbraun** [comment]
@vinitkumar Fair point!! Just added them. The JS now uses `()=>{}` notation. I.e., there is a change.

**Pull request merged**
